[package]
name = "stock-ranker-wasm"
edition.workspace = true
publish.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
schema = { path = "../../json-schema/rust" }
serde_json = "1"
stock-ranker = { path = "../main" }
wasm-bindgen = "0.2"
