on:
  - push
  - pull_request
env:
  RUSTFLAGS: "--deny warnings"
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: seamlik/devops/.github/actions/cache-nodejs@2.1.0
      - uses: seamlik/devops/.github/actions/cache-rust@2.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm install
      - run: sudo apt-get update
      - run: sudo apt-get install --yes ninja-build

      # Verify
      - run: ninja format
      - uses: seamlik/devops/.github/actions/check-formatting@2.1.0
      - run: ninja verify
