on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/seamlik/invest-toy-builder:latest
      env:
        # GitHub Actions modifies the home directory
        CARGO_HOME: /root/.cargo
        RUSTUP_HOME: /root/.rustup
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: "Circumvent that GitHub Actions checks out the repository using another user"
        run: chown --recursive 0:0 .
      - run: ninja init

      # Verify
      - run: ninja format
      - uses: seamlik/devops/.github/actions/check-formatting@2.1.0
      - run: ninja verify
